ecommerceproject/ecommerce/cartapp/urls.py
from django.urls import path, include

from cartapp import views
app_name = 'cartapp'
urlpatterns = [

    path('Add/<int:product_id>',views.AddtoCart,name='add_cart'),
    path('remove/<int:product_id>',views.cart_remove,name='remove_cart'),
    path('',views.cart_detail,name='to_cart'),
    path('delete/<int:product_id>',views.full_remove,name='full_remove'),

]

ecommerceproject/ecommerce/ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('search/',include('searchapp.urls')),
    path('cart/', include('cartapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/ecommerce/searchapp/urls.py
from django.urls import path, include

from searchapp import views
app_name = 'search_app'
urlpatterns = [

    path('',views.SearchResult,name='to_search'),

]

ecommerceproject/ecommerce/shop/urls.py
from django.urls import path

from shop import views
app_name = 'shopapp'
urlpatterns = [

    path('',views.allprodcat,name='allprodcat'),
    path('<slug:c_slug>/',views.allprodcat,name='Prod_by_cat'),
    path('<slug:c_slug>/<slug:product_slug>',views.ProdDetail,name='Prod_detail'),

]

ecommerceproject/ecommerce/cartapp/models.py
from django.db import models

# Create your models here.
from shop.models import Product
class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
         db_table = 'Cart'
         ordering = ['date_added']
    def __str__(self):
        return self.cart_id
class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return self.product

ecommerceproject/ecommerce/searchapp/models.py
from django.db import models

# Create your models here.

ecommerceproject/ecommerce/shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    desc = models.TextField(blank=True)
    image = models.ImageField(upload_to='category',blank=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def get_url(self):
        return reverse('shopapp:Prod_by_cat',args=[self.slug])
    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250,unique=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stocks = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
    def get_url(self):
        return reverse('shopapp:Prod_detail',args=[self.category.slug,self.slug])
    def __str__(self):
        return '{}'.format(self.name)

ecommerceproject/ecommerce/cartapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from .models import CartItem,Cart
from shop.models import Product
# Create your views here.
def createId(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart
def AddtoCart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=createId(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id = createId(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stocks:
            cart_item.quantity+=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product,quantity=1,cart=cart)
    return redirect('cartapp:to_cart')
def cart_detail(request,total = 0,counter = 0,cart_items = None):
    try:
        cart = Cart.objects.get(cart_id=createId(request))
        cart_items = CartItem.objects.all().filter(cart=cart,active = True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))
def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=createId(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cartapp:to_cart')
def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=createId(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cartapp:to_cart')

ecommerceproject/ecommerce/searchapp/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.


def SearchResult(request):
    products = None
    query = None

    if request.method == "GET":
        query = request.GET.get('search_term')
        print(query)
        products = Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

ecommerceproject/ecommerce/shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.

def allprodcat(request,c_slug=None):
    c_page = None
    cat = Category.objects.all()
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug = c_slug)
        print(type(c_page))

        products_list = Product.objects.all().filter(category=c_page,available=True)

    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list,6)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page, 'products':products,'cat': cat})
def ProdDetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,"product.html",{'product':product})

ecommerceproject/ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescreption %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a69aeed373.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="body" style="background-color:#F6F899">
 <div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
 </div>

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>


</body>
</html>

ecommerceproject/ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static%}
{% block metadescription %}
Search results
{% endblock %}
{% block title %}
Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
        <div>
            <br>
            <div class="row-mx-auto text-center">
                <img src="{% static 'img/empty.png' %}" width="60px" height="60px" alt="Empty cart" >
                <h3><b>Hey! No items in your cart!!!</b></h3>
            </div>
            <br>
            <div class="row-mx-auto text-center">
                <a href="{% url 'shopapp:allprodcat' %}"><button  class="btn btn-primary btn-lg" style="background-color:#439E1B">Continue shopping</button></a>
            </div>
        </div>
        {% else %}
        <div>
            <div>
                <h2>Items in your cart</h2>
            </div>
        </div>
<div class="row">
    <div class="col-md-8">
        <table class="table">
            <thead>
                <tr class="table-info">
                    <th colspan="5" class="text-center">
                        Your Items
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td class="table-warning">
                   <a href="{{cart_item.product.get_url}}"><img src="{{cart_item.product.image.url}}" height="100px" width="150px" style="border-radius:50%" alt="{{cart_item.product.name}}"></a>
                </td>
                <td class="table-active">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Price:$ {{cart_item.product.price}}
                    <br>
                    No.of items:  {{cart_item.quantity}} X {{cart_item.product.price}}
                    <br>
                    Item total price:{{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stocks %}
                <td class="table-danger">
                    &emsp;<a href="{% url 'cartapp:add_cart' cart_item.product.id %}"><i class="fa-solid fa-plus fa-lg" style="color: #112a55;"></i></a>
                    &emsp;<a href="{% url 'cartapp:remove_cart' cart_item.product.id %}" ><i class="fa-solid fa-minus fa-lg" style="color: #e10e43;"></i></a>
                    &emsp;<a href="{% url 'cartapp:full_remove' cart_item.product.id %}"><i class="fa-solid fa-trash" style="color: #dd0e2d;"></i></a>
                </td>
                {% else %}
                <td>
                    &emsp;<a href="{% url 'cartapp:remove_cart' cart_item.product.id %}" ><i class="fa-solid fa-minus fa-lg" style="color: #e10e43;"></i></a>
                    &emsp;<a href="{% url 'cartapp:full_remove' cart_item.product.id %}"><i class="fa-solid fa-trash" style="color: #dd0e2d;"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-md-4">
        <table>
            <thead>
            <tr>
                <th  class="text-center table-success">
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
               <td class="table-success">
                   Your shopping total : <strong>{{total}}</strong>
               </td>
            </tr>
            <tr>
                <td class="table-success">
                    Please review your shopping experience &emsp;<i class="fa-regular fa-face-smile" style="color: #f1300e;"></i> <i class="fa-regular fa-face-smile" style="color: #f1300e;"></i>
                </td>
            </tr>
            <tr>
                <td class="table-success">
                <a href="{% url 'shopapp:allprodcat' %}"><button  class="btn btn-primary btn-lg" style="background-color:#439E1B">Continue shopping</button></a>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shopapp:allprodcat' %}"></a>
        </div>
    </div>
</div>



 {% endif %}

{% endblock %}

ecommerceproject/ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static%}
{% block metadescription %}
{% if category %}
    {{category.desc|truncatewords:155}}
{% else %}
    Welcome to online shoppy . All things you want ..
{% endif %}
{% endblock %}
{% block title %}
{% if category %}
    {{category.name}} - Online shoppy
{% else %}
    See our new collections - Online shoppy
{% endif %}
{% endblock %}
{% block content %}
{% if category %}
<div>
    <div>
        <p><a href="{% url 'shopapp:allprodcat' %}"> <h5>Our product collection</h5></a> </p>
    </div>
</div>
{% endif %}
<div>
{% if category %}

    <center><img src="{{category.image.url}}" alt="{{category.name}}"></center>
</div>
<br>
<div>
    <h1>{{category.name}}</h1>
    <p>{{category.desc}}</p>
    <div class="row">
    {% for product in products.object_list %}
    <div class="col-md-2">
        <div>
            <a href="{{product.get_url}}"><img src="{{product.image.url}}" height="66" width="100" alt="{{product.name}}"></a>
            <p style="font-size:20px"><b>{{product.name}}</b></p>
            <p>Price: {{product.price}}</p>
        </div>

    </div>
                {% endfor %}
        </div>
    <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                <a href="page={{pg}}" class="btn btn-light-btn-sm {% if products.number == pg %} active {% endif %}">{{pg}} </a>
                {% endfor %}
            </div>
            {% endif %}

</div>

{% else %}

<div>
<img src="{% static 'img/banner.png' %}" width="1450px" height="800px" alt="our products">
</div>
    <br>
<div class="container" style="background-color:#A3C345; border-radius:5%">

    <center><h1>Our collections</h1></center>
    <p>Lorem ipsum dolor sit amet, consectetur
        adipiscing elit, sed do eiusmod tempor incididunt
        ut labore et dolore magna aliqua. Non odio euismod lacinia
        at quis. Cras adipiscing enim eu turpis egestas pretium. Id nibh
        tortor id aliquet. Lobortis mattis aliquam faucibus purus in massa
        tempor. Vitae ultricies leo integer malesuada nunc vel risus commodo viverra
        . Mi bibendum neque egestas congue quisque egestas diam. Eget duis at tellus
        at urna.</p>
</div>

<div class="row" style="background-color:#D7D95B">
    <h2 style="background-color:#ADAF38"><center>Categories</center></h2>
    <br>
    <br>
{% for i in cat %}
    <div class="col-sm-2">&emsp;
        <div class="card" style="background-color:#8D770D; border-radius:75%">
            <div class="card_img">
            <a href="{{i.get_url}}"><img src="{{i.image.url}}"></a>
            </div>
            <div class="card_info">

        </div>
</div>
        <h5><center>{{i.name}}</center></h5>
    </div>
{% endfor %}
</div>


<br>

{% endif %}
{% endblock %}

ecommerceproject/ecommerce/templates/footer.html
<div class="footer">
  <p class="text-center">&copy: Online shoppy app.All rights Reserved</p>
</div>

ecommerceproject/ecommerce/templates/header.html
{% load static %}
<header>
    <div class="row">
        <div class="col-md-3" style="background-color:#F998A6">
            <center><h1>Online Shoppy</h1>
            <h6>All things You wish</h6></center>
        </div>
        <div class="col-md-9">
        <center>
        <a href="{% url 'shopapp:allprodcat' %}">
            <img src="{% static 'img/logo.png' %}" width="50px" height="65px" alt="logo_image" >
        </a>
    </center>
            </div>
    </div>

</header>

ecommerceproject/ecommerce/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light"  >
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse"  id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shopapp:allprodcat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shopspp' in request.path %}active{% endif %}" >
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            collections
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li style="background-color:#F9B6BF"><a class="dropdown-item" href="{% url 'shopapp:allprodcat' %}" >Categories</a></li>
            {% for cat in links %}
            <li style="background-color:#F9B6BF"><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
            <li><hr class="dropdown-divider"></li>
          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cartapp:to_cart' %}"><i class="fa-solid fa-cart-shopping fa-lg" style="color: #b9274c;"><p style="color:red;font-family: 'Roboto Slab', serif;font-size:14px;">&emsp;({{item_count}})</p></i></a>
        </li>
      </ul>
      <form method="get" action="{% url 'search_app:to_search' %}" >
        {% csrf_token %}
        <input type="search" name="search_term" placeholder="Search">
        <button  class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass fa-lg" style="color: #ab2b5e;"></i></button>
<!--        <input type="submit">-->
      </form>
    </div>
  </div>
</nav>

ecommerceproject/ecommerce/templates/nav1.html
<nav class="navbar navbar-expand-lg navbar-light bg-light"  >
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse"  id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shopapp:allprodcat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shopspp' in request.path %}active{% endif %}" >
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            collections
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li style="background-color:#F9B6BF"><a class="dropdown-item" href="{% url 'shopapp:allprodcat' %}" >Categories</a></li>
            {% for cat in links %}
            <li style="background-color:#F9B6BF"><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
            <li><hr class="dropdown-divider"></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=""><i class="fa-solid fa-cart-shopping fa-beat fa-lg" style="color: #b9274c;"></i></a>
        </li>
      </ul>
      <form method="get" action="{% url 'search_app:to_search' %}" >
        {% csrf_token %}
        <input type="search" placeholder="Search">
        <button  class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass fa-beat fa-lg" style="color: #ab2b5e;"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerceproject/ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static%}
{% block metadescription %}
    {{product.desc|truncatewords:155}}
    Welcome to online shoppy . All things you want ..
{% endblock %}
{% block title %}
{% if category %}
    {{product.name}} - Online shoppy
{% endif %}
{% endblock %}
{% block content %}
<div>
    <div>
        <h5><a href="{% url 'shopapp:allprodcat' %}">Home</a>&emsp;|&emsp;
            <a href="{{product.category.get_url}}">{{product.category}}</a>&emsp;|&emsp;{{product.name}} </h5></p>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-6">
        <div>
            <center><img src="{{product.image.url}}" alt="{{product.name}}"></center>
        </div>
    </div>
    <div class="col-md-6">
        <h1><b>{{product.name}}</b></h1>
        <h3><b>Price:</b>&emsp;${{product.price}}</h3>
        <h4><b>About Product:</b></h4>
        <p>&emsp;{{product.desc}}</p>
        {% if product.stocks <= 0 %}
        <center><h3 style="color:red"><b>Out of stock</b></h3></center>
        {% else %}
        <center><a href="{% url 'cartapp:add_cart' product.id %}"><button type="button" class="btn btn-primary btn-lg">Add to cart</button></a>&emsp;
        <a href=""><button type="button" class="btn btn-primary btn-lg" style="background-color:#439E1B">Wishlist item</button></a>
        </center>
        {% endif %}
    </div>
</div>
{% endblock %}

ecommerceproject/ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static%}
{% block metadescription %}
Search results
{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
<!-- On rows -->
<tr class="table-active">...</tr>

<tr class="table-primary">...</tr>
<tr class="table-secondary">...</tr>
<tr class="table-success">...</tr>
<tr class="table-danger">...</tr>
<tr class="table-warning">...</tr>
<tr class="table-info">...</tr>
<tr class="table-light">...</tr>
<tr class="table-dark">...</tr>

<!-- On cells (`td` or `th`) -->
<tr>
  <td class="table-active">...</td>

  <td class="table-primary">...</td>
  <td class="table-secondary">...</td>
  <td class="table-success">...</td>
  <td class="table-danger">...</td>
  <td class="table-warning">...</td>
  <td class="table-info">...</td>
  <td class="table-light">...</td>
  <td class="table-dark">...</td>
</tr>
  </tbody>
</table>
<div>
    <h3 class="text-center my_search"> Results found for <b>"{{query}}"</b></h3>
    <br>
    <div class="row">
    {% for product in products %}
    <div class="col-md-2">
        <div>
            <a href="{{product.get_url}}"><img src="{{product.image.url}}" height="66" width="100" alt="{{product.name}}"></a>
            <p style="font-size:20px"><b>{{product.name}}</b></p>
            <p>Price: {{product.price}}</p>
        </div>

    </div>
    {% empty %}
        <div class="row-mx-auto text-center">
            <h3><b>0 results found</b></h3>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}